#!/bin/bash

# Setup zram on setup
if grep -q "/dev/zram0" /proc/swaps; then
    echo "zram is already configured"
else
    total_mem=$(grep MemTotal /proc/meminfo | awk '{print $2 * 1024}')
    zram_size=$(echo "$total_mem * 0.55" | bc | cut -d'.' -f1)

    echo "$zram_size" > /sys/block/zram0/disksize
    echo "100" > /proc/sys/vm/swappiness
    echo "lz4" > /sys/block/zram0/comp_algorithm
    echo "0" > /proc/sys/vm/page-cluster
    echo "false" > /sys/kernel/mm/swap/vma_ra_enabled

    mkswap /dev/zram0
    swapon -p -3 /dev/zram0
fi

# Allow user to access touchscreen nodes and flashlight
[ -e "/sys/kernel/furilabs/palmrejectionmode/common_node/" ] && chown 32011:32011 /sys/kernel/furilabs/palmrejectionmode/common_node/*mode
[ -e "/sys/class/flashlight/mt-flash-led1/" ] && chown 32011:32011 /sys/class/flashlight/mt-flash-led1/*
[ -e "/sys/class/flashlight/mt-flash-led2/" ] && chown 32011:32011 /sys/class/flashlight/mt-flash-led2/*

# Wait for WLAN to come up
while [ "`getprop vendor.connsys.driver.ready`" != "yes" ]; do
    sleep 1
done

sleep 3

# Enable WiFi
echo 1 > /dev/wmtWifi

while [ ! -e /sys/class/ieee80211/phy0 ]; do
    sleep 1
done

# Enable wake on lan magic packet
iw phy phy0 wowlan enable magic-packet

# Disable wmt driver debugging
echo "0xFF:0x03" > /proc/net/wlan/dbgLevel

# Disable statsd since its unused
setprop ctl.stop statsd

# Wait for binder nodes to come up and give them the right permission
while [ ! -e /dev/binderfs/anbox-binder ]; do
    sleep 1
done

chmod 666 /dev/binderfs/anbox-*

chown 32011:32011 /dev/binderfs/anbox-*

# Wait for vibrator driver to come up and give it the right permission
while [ ! -e /sys/class/leds/vibrator/activate ]; do
    sleep 1
done

chown 32011:32011 /sys/class/leds/vibrator/*

# Allow to access brightness nodes
[ -e "/sys/class/leds/green/" ] && chown 32011:32011 /sys/class/leds/green/*
[ -e "/sys/class/flashlight_core/flashlight/" ] && chown 32011:32011 /sys/class/flashlight_core/flashlight/*
[ -e "/sys/class/leds/lcd-backlight/" ] && chown 32011:32011 /sys/class/leds/lcd-backlight/*

# Disable coredumps
sysctl -w kernel.core_pattern=|/bin/false

exit 0
